### ISSUE TITLE
Does not respect `numWorkers` arg when using an object as first arg

### ISSUE THREAD

**Issue by jrf0110** [brianc/node-forky#10]
__master.js__

```javascript
require('forky')({ path: __dirname + '/worker.js' }, 1 );
```

__worker.js__

```javascript
console.log( 'Hello from worker', require('cluster').worker.id );
require('http').createServer( function( req, res ){ } );
```

`node master`

```
Hello from worker 1
Hello from worker 3
Hello from worker 2
Hello from worker 4
```

If you change the __master.js__ to:

```javascript
require('forky')( __dirname + '/worker.js', 1 );
```

it works fine

**Comment by jrf0110** [comment]
Browsing the source, I think this may be from maintaining some backwards compatibility? Either way, I'd suggest just making the interface more rigid, or use something like https://github.com/jrf0110/leFunc#overload-your-functions-with-lefunc manage all those function argument signatures

**Comment by AndrewBarba** [comment]
I wouldn't consider this an issue but more of an incorrect use of the api when passing in an object. It is pretty clearly documented that if you want to pass in an object you need to be using the correct parameters:
```
const forky = require('forky');
forky({
  path: __dirname + '/server.js',
  workers: process.env.THREADS || 1,
  enable_logging: true
});
```

**Comment by jrf0110** [comment]
Yeah, my confusion was a result of looking at some of my old code using forky and copying pasting with some newer code. When forky didn't work as I expected, I opened the module in my editor and saw this line: https://github.com/brianc/node-forky/blob/master/index.js#L46

```javascript
var forky = module.exports = function(options, workerCount, cb) {
```

And thought that it was _pretty clear_ that the first argument is an object and the second argument is a number.

However, I'm just using the options object and now forky is worky. :+1:
